services:
  postgres:
    image: postgres:17.2
    container_name: postgres17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: a
      POSTGRES_DB: magpie_pools
      POSTGRES_USER: jini
    volumes:
      - ./postgres-data-dev:/var/lib/postgresql/data
    networks:
      - magpie-pools-network

  cli:
    build:
      context: .
      dockerfile: ./cli/Dockerfile
    volumes:
      - ./src/storage/database/migrations/:/app/src/storage/database/migrations
    networks:
      - magpie-pools-network
    depends_on:
      - postgres

networks:
  magpie-pools-network:
